//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public int c_id { get; set; }
        public Nullable<int> i_id { get; set; }
        public string c_introduce { get; set; }
        public string c_counselor { get; set; }
        public string c_classname { get; set; }
        public string c_school { get; set; }
        public string c_college { get; set; }
    }
}
