//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveword
    {
        public int lw_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public string lw_contetn { get; set; }
        public Nullable<System.DateTime> lw_time { get; set; }
        public Nullable<byte> lw_read { get; set; }
        public Nullable<int> lw_getperson { get; set; }
        public Nullable<int> lw_pid { get; set; }
    
        public virtual users users { get; set; }
    }
}
