//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class resources
    {
        public int r_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public string r_url { get; set; }
        public Nullable<System.DateTime> r_date { get; set; }
        public string r_title { get; set; }
        public string r_introduce { get; set; }
    }
}
