//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.leaveword = new HashSet<leaveword>();
        }
    
        public int u_id { get; set; }
        public Nullable<int> ut_id { get; set; }
        public string u_account { get; set; }
        public string u_password { get; set; }
        public string u_gender { get; set; }
        public string u_stucentid { get; set; }
        public string u_name { get; set; }
        public string u_political { get; set; }
        public string u_badroom { get; set; }
        public string u_phone { get; set; }
        public string u_qq { get; set; }
        public Nullable<System.DateTime> u_birthday { get; set; }
        public string u_hometown { get; set; }
        public string u_nation { get; set; }
        public Nullable<System.DateTime> u_lastlogintime { get; set; }
        public string u_lastloginip { get; set; }
        public Nullable<int> u_logintime { get; set; }
    
        public virtual ICollection<leaveword> leaveword { get; set; }
    }
}
